language: python

python:
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install nose

script: nosetests

notifications:
  slack:
    secure: kC0zn73oJd5sO3pvl5V7Ua5ttTXA3uH2FyyYR3eMvSily1MzIX4kd62LnuVb9b30l+wkfpy8m22CmduNIf1tM/Q0LW4TkLLMVkxe5YaP47MRISd8oznH+kOvTISey3/USozJ+hL9gyNuYW+q7dvu44JqSIzKu9W1UVAvnE4EZynBEeY4HUYo5gBkiiXz3O1Q3xSps1Lvfp6VhQPsUn5unNHqCl3hAmwRhfcHZOJBA0CYXDKFf79urGuCxvaeECFRfVbljgzD6p1BdA+mzZPHFYlrW9YogTAqeslOFPQXw9X36j5dLB9hqA0zlQIpe1iB0tFdnAxuHqPhr8x0ezFXASva2THhd7sCgfy0/TbxH0TDVaVawCGZTtBTsR65BqbFyOAzrSCqFU2yDvMWguUYLWYN+bL+IMemODJ/HdSR6tLRJAkdfCDRNN02/aHltvpwl7SSg+vns8ZFuEHPO85XHSR1y00rzpLkBlZsiEFMiv9c5Wk97CLSg1nPjL5srQ3xyr/yjh/XQxAX0Z2rPKSzMnu6syQO+GdQM600gsT4GZEMjYb+KpAt63nSkojM/HQ+VYdrasGN3AVjUMod+c9a1DUcsijriCuD/O3hjEi4q53SUJX/1QIerwGCVheu+eH84nLTziCPQgXZ9m7Yt9i9fS/e2aL/yaoSjYpCypnXw2o=
